package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"strconv"
	"fmt"

	"cms-backend/internal/graphql/generated"
	"cms-backend/internal/services"
)

// Create is the resolver for the create field.
func (r *mutationResolver) Create(ctx context.Context, service string, data map[string]interface{}) (map[string]interface{}, error) {
	// Get UserID from context if authenticated
	userID := uint(1)
	if v, ok := ctx.Value("user_id").(uint); ok {
		userID = v
	}
	return r.DataSvc.CreateData(ctx, service, data, userID)
}

// Update is the resolver for the update field.
func (r *mutationResolver) Update(ctx context.Context, service string, id string, data map[string]interface{}) (map[string]interface{}, error) {
	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %v", err)
	}
	userID := uint(1)
	if v, ok := ctx.Value("user_id").(uint); ok {
		userID = v
	}
	return r.DataSvc.UpdateData(ctx, service, uint(uid), data, userID)
}

// Delete is the resolver for the delete field.
func (r *mutationResolver) Delete(ctx context.Context, service string, id string) (*bool, error) {
	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %v", err)
	}
	err = r.DataSvc.DeleteData(ctx, service, uint(uid))
	if err != nil {
		return nil, err
	}
	success := true
	return &success, nil
}

// Data is the resolver for the data field.
func (r *queryResolver) Data(ctx context.Context, service string, id string) (map[string]interface{}, error) {
	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %v", err)
	}
	return r.DataSvc.GetData(ctx, service, uint(uid), nil)
}

// List is the resolver for the list field.
func (r *queryResolver) List(ctx context.Context, service string, page *int, limit *int, search *string) ([]map[string]interface{}, error) {
	p := 1
	if page != nil && *page > 0 {
		p = *page
	}
	sz := 20
	if limit != nil && *limit > 0 {
		sz = *limit
	}
	s := ""
	if search != nil {
		s = *search
	}

	req := &services.ListDataRequest{
		Page:     p,
		PageSize: sz,
		Search:   s,
	}
	rows, _, err := r.DataSvc.ListData(ctx, service, req)
	return rows, err
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
